jobs:
- job: VS2015Hosted
  pool:
    vmImage: vs2015-win2012r2
  steps:
    - template: azure-pipelines-steps.yml

- job: VS2017Hosted2017
  pool:
    vmImage: vs2017-win2016
  steps:
    - template: azure-pipelines-steps.yml

- job: VS2019Hosted2019
  pool:
    vmImage: windows-2019
  steps:
    - template: azure-pipelines-steps.yml
 
- job: HostedWindowsContainer
  pool:
    vmImage: win1803
  steps:
    - template: azure-pipelines-steps.yml

- job: linuxUbuntu
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: azure-pipelines-steps.yml

- job: macOSMojave1014
  pool:
    vmImage: macos-10.14
  steps:
    - template: azure-pipelines-steps.yml

- job: macOSMojave1013
  pool:
    vmImage: macos-10.13
  steps:
    - template: azure-pipelines-steps.yml